export const KEY_VALUE_KEYS = Object.freeze({
  issuanceTasks: 'issuance_tasks',
  preIssuanceTasks: 'preissuance_tasks',
  assetCreateTasks: 'asset_create_tasks',
  saleCreateTasks: 'sale_create_tasks:*',
  withdrawalTasks: 'withdrawal_tasks',
  amlAlertTasks: 'aml_alert_tasks',
  atomicSwapBidTasks: 'atomic_swap_bid_tasks:*',
  atomicSwapAskTasks: 'atomic_swap_ask_tasks',
  paymentCreateTasks: 'payment_tasks:*',
  createPollTasks: 'create_poll_tasks:*',
  change_role_tasks: 'change_role_tasks:*:*',
  kycRecoveryEnabled: 'kyc_recovery_enabled',
  kycRecoverySignerRole: 'kyc_recovery_signer_role',
  createKycRecoveryTasks: 'create_kyc_recovery_tasks',
  createOfferTasks: 'create_offer_tasks',
  removeOfferTasks: 'remove_offer_tasks',
  redemptionTasks: 'redemption_tasks',
  signerRoleDefault: 'signer_role:default',
  signerRoleIssuance: 'signer_role:issuance'
})
